name: main

on:
  push:
    branches:
      - main

jobs:
  build:
    name: build and publish
    runs-on: ubuntu-latest

    permissions:
      contents: write
      id-token: write

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - uses: actions/setup-node@v4
        with:
          # node-version the same as in `mymindstorm/setup-emsdk`
          node-version: "18.20.3"
          registry-url: "https://registry.npmjs.org"

      - uses: mymindstorm/setup-emsdk@v14

      - name: Build
        run: node build.js

      - run: node publish.js
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update wasm artifacts
