name: main

on:
  push:
    branches:
      - main

jobs:
  build:
    name: build and publish
    # timeout-minutes: 15
    runs-on: ubuntu-latest

    permissions:
      contents: write
      id-token: write

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      # - uses: pnpm/action-setup@v3
      #   with:
      #     version: 8
      #     run_install: false

      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          registry-url: "https://registry.npmjs.org"
          # cache: "pnpm"

      - uses: mymindstorm/setup-emsdk@v14

      - name: Build
        run: node build.js

      - run: node publish.js
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update wasm artifacts

      # - run: npm publish --provenance --access public
      #   env:
      #     NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
